name: Tests

on:
  push:

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python$v4
        with: 
          python-version: 3.12

      - name: Run tests
        run: python run_tests.py 